config/routes.rb
DynamicItens::Application.routes.draw do
  
  devise_for :admins 

	root to: "admins/items#index"

	namespace :admins do
		resources :items, only: [:create,:new,:index] do
			collection do	
				get "update_position"
				get "sort_by_name"
			end			
		end
	end

end

app/models/admin.rb
class Admin < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me
  
end

app/models/item.rb
class Item < ActiveRecord::Base

  include Sortable::Position

  attr_accessible :name, :position
  validates_presence_of :name

  before_save :set_position
  default_scope order("position")

  def self.by_name
    Item.unscoped { Item.find(:all, order: "name", select: "id").map { |item| item.id }} 
  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
	
	before_filter :authenticate_admin!
	
	def index
		@items = Item.all
		respond_with @items
	end

	def new
		@item = Item.new
		respond_with @item
	end

	def create
		@item = Item.new(params[:item])
		@item.save
		redirect_to root_path
	end

	def update_position
		Item.update_position(params[:items])
		render nothing: true
	end

	def sort_by_name
		Item.update_position(Item.by_name)
		redirect_to root_path
	end

end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admins/items/_form.html.erb
<%= simple_form_for @item , url: :admins_items do |f| %>
	<%= f.input :name %>
	<%= f.submit %>
<%end%>

app/views/admins/items/index.html.erb
<% unless @items.empty? %>
	<ul class="menu_admin">
		<li id="sort">
			<%= link_to "Ordenar por Alfabetização", sort_by_name_admins_items_path %>
		</li>
	</ul>

	<ul id="sortable">
		<% @items.each do |item| %>
			<li class="ui-state-default" idItem="<%= item.id%>" >
				<span class="ui-icon ui-icon-arrowthick-2-n-s"></span>
					<%= item.name %>
			</li>
		<%end%>
	</ul>
<%end%>

app/views/admins/items/new.html.erb
<%= render "form" %>

app/views/admins/menu/_items.html.erb
<% if admin_signed_in? %>
	<li>
		<%= link_to "Home", admins_items_path %>
	</li>
	<li>
		<%= link_to "New Item", new_admins_item_path %>
	</li>
<%end%>

app/views/layouts/_contener_top.html.erb
<div class="contener_top">
</div>

app/views/layouts/_footer.html.erb
<div class="footer"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DynamicItens</title>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/contener_top'%>

<div class="structure">

	<p style="color: green"><%= flash[:notice] %></p>

	<ul class="menu_admin">
	  <%= render 'admins/menu/items' %>
	</ul>

	<div class="contener_body">

		<%= yield %>

	</div>

</div>

<%= render 'layouts/footer' %>

</body>
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag "application" %>
</html>